### ISSUE TITLE
Add protobuf-rpc support for lbrynet-daemon

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry#1010]
We should add support for serialized protobuf api requests and responses. This would allow the api functions to have their parameters, responses, and docs be well defined and re-usable between projects.

Proposal:

- Make a new `lbryschema.proto` repo, move [lbryschema/lbryschema/proto](https://github.com/lbryio/lbryschema/tree/master/lbryschema/proto) to `lbryschema.proto/claim`, and add the new definitions to `lbryschema.proto/rpc`.

- Create `RPCServer` interface in lbrynet, convert `Daemon` to implement it (rather than inheriting `AuthJSONRPCServer`). Change `AuthJSONRPCServer` to inherit `Daemon` and implement json specific functionality, and add `AuthProtoRPCServer` to implement the proto specific stuff.

- look at https://grpc.io/

**Comment by jackrobison** [comment]
Related issues:

https://github.com/lbryio/lbry/issues/1006
https://github.com/lbryio/lbry/issues/1008

**Comment by kauffj** [comment]
I'm open to supporting returning Protobuf responses, but I'm not sure this addresses the root issue, which is the desire to have one definition for a type (say a `Claim` or a `File`) and have that definition be portable to as many languages as possible.

Having applications use Protobuf directly may solve the data checking side of things, but it does nothing to actually provide shared type definitions.

**Comment by kaykurokawa** [comment]
I agree with jeremy. #1006 and #1008 should be fixed first before this, not the other way around. 

Protobuf is overkill to fix the root issue, which is that we have ambiguous and unenforced return values from functions, most problematically in lbryum and lbryum-server functions. This can be mitigated in Python by using pre-defined classes or namedtuples (https://docs.python.org/2/library/collections.html#collections.namedtuple) for return values instead of dictionaries.

**Comment by eukreign** [comment]
The official SDK should just support JSON-RPC. We'll leave exotic RPC extensions for community contributions.
