### ISSUE TITLE
Add new startup stage to indicate that an encrypted wallet is waiting for a password

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry#1035]
With wallet encryption implemented, if a wallet is encrypted, the wallet needs to be unlocked before daemon startup completes.

Currently, when the daemon is waiting for the wallet password, the `startup_status` value returned for the  `status` command goes like so.
```
"startup_status": {
    "code": "loading_wallet",
    "message": "Catching up with the blockchain"
}
```

I believe we should add a new code and a more meaningful message to indicate that the wallet is actually waiting for a password at this stage, since the above is also returned after the blockchain has been caught up with.

**Comment by tzarebczan** [comment]
With other encrypted wallets I've used, you didn't actually need a password unless you were performing a function that required a transaction/signing. How/why is this different for us? Can't we still read the wallet txs and channel certificates without unlocking the wallet?

**Comment by kaykurokawa** [comment]
@tzarebczn, 
Its because during downloading, the client may need to pay multiple servers data fee(this functionality does not exist yet however) . Unfinished downloads start on startup and there is also auto-renew feature which depends on the password.  Overall, we just make the assumption in lbrynet that the wallet is always unlocked so there might be other issues I'm forgetting about.

@akinwale, I think this is a good idea. Maybe "code" could be "waiting_on_wallet_unlock" and "message" could be "waiting for user to unlock the wallet using wallet_unlock command".
