### ISSUE TITLE
Exclude blocked content from official LBRY nodes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1105]
## The Issue
To go along with https://github.com/lbryio/lbry-app/issues/565, the daemon should abide by the blacklist (https://api.lbry.io/file/list_blocked) and take the necessary actions when an outpoint is found on an official LBRY node.  

We should discuss what this actually means - does it stop announcement of the content, is the content purged? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
i suggest that blocked content:
- does not resolve
- does not download
- does not appear in lists of non-local content (e.g. channel_list)
- is not announced???

the daemon should NOT do any of this:
- delete content off the user's machine
- hide it from lists of local content (e.g. file_list)

most of this can be done at the lbryumx level, so maybe doing it there is enough. blocking announcement must be done in the daemon, but i'm open to arguments that we should not be blocking announcement of content you already have.

in terms of implementation, i think the blocked content list should be isolated and flexible. perhaps users will want to add other community-run blocklists in the future.

@eukreign do you agree?

**Comment by eukreign** [comment]
If we want to support customized block lists then doing this at lbryumx layer probably would be much harder (since then we'd have to implement blocking both in lbryumx for the official block list maintained by LBRY Inc and in daemon/desktop app for user customizeable block lists)? I think we should do this solely in the daemon/client?

On the other hand, if we start adding more daemon implementations in other languages, we'd have to reimplement this blocking feature in each version...

Hmm, is there a way to have official block list and popular community block lists at the lbryumx side (as a sort of hybrid solution)? @shyba 

Perhaps lbrumx could have the official LBRY blocklist and then other groups that want to maintain block lists can do a PR or request that a URL be added to lbryumx for their blocklist and become an option to users using that lbryumx instance. When clients do a resolve to lbryumx they would provide the block lists names supported by that lbryumx server that they would like to have the resolve filtered by?

Are there legal implications we should be concerned about regarding where the blocking happens?

**Comment by tzarebczan** [comment]
Would like @kauffj to chime in here - I think he was originally against blocking any URIs at the wallet / protocol level. But I've also heard mentions of a stream blacklist for nodes.

**Comment by kauffj** [comment]
My understanding is that we do not have a legal obligation to perform blocking at this level, just as someone writing an HTTP daemon or BitTorrent daemon would not have an obligation.

I support adding this as a _feature_ to support users who may not want to host certain types of content.

Whatever happens here, if adding to the daemon layer it ought to be done in a configurable way. The blacklists LBRY maintains would represent data known to be illegal in the United States. A user in South Korea would likely want to respect a different list representing content known to be illegal there.

While we've gotten legal consultation on this before, we ought to do another round with any proposed design before implementing it, or @finer9 should chime in that he thinks this is a priority to remain compliant.

**Comment by finer9** [comment]
My current understanding is that our obligation is to block in a way that will restrict the content from the majority of users.  For now, that is the app.  If someone had the ability to get to blocked content programatically through their own effort using the daemon, their own actions speak to the intent, and they are bypassing our good-enough-for-most method of blocking.  Clearly something like HTTP does not have anything blocked at the protocol level
