### ISSUE TITLE
Deprecation warning (API)

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry#1123]
## The Issue
I don't get any warnings for deprecated commands usign the api.
( Also api docs are outdated )

### Steps to reproduce
1. Just call a deprecated command (`send_amount_to_address`)
See example: https://github.com/lbryio/lbry/issues/1123#issuecomment-367565815

### Expected behaviour
> I think the behavior should be consistent across the API and CLI
https://github.com/lbryio/lbry/issues/1123#issuecomment-367573379

It should provide / show a deprecation `warning / error`:
``` SHELL
   Deprecated send_amount_to_address in favor of wallet_send
```

**Comment by kauffj** [comment]
@hackrush01 are you working on this? It is really embarrassing to me to continue to have this happen to valuable contributors.

@btzr-io for whatever reason, the CLI docs are always up to date, so I recommend using those instead.

**Comment by kauffj** [comment]
Also @btzr-io I hope this means you're back! You'd love some of the design work @seanyesmunt and Nicolas have been working on.

**Comment by hackrush01** [comment]
@kauffj Yes this is what I'm currently working on.
@btzr-io can you please test and let me know whether the same command, when
called from cli, gives the deprecated command warning?

Kind Regards
Amit Tulshyan

On Feb 22, 2018 3:29 AM, "Jeremy Kauffman" <notifications@github.com> wrote:

@hackrush01 <https://github.com/hackrush01> are you working on this? It is
really embarrassing to me to continue to have this happen to valuable
contributors.

@btzr-io <https://github.com/btzr-io> for whatever reason, the CLI docs are
always up to date, so I recommend using those instead.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lbryio/lbry/issues/1123#issuecomment-367488681>, or mute
the thread

**Comment by btzr-io** [comment]
@hackrush01 Tested latest version v0.19.0rc36

#### LBRY-CLI
Shows a deprecation error :+1: 
```SHELL
$ ./lbrynet-cli channel_list_mine
ERROR: "channel_list_mine" is deprecated, using "channel_list".
See `lbrynet-cli help` for more information.
[]

```
#### LBRY-API
The command works but there is no warning :confused: 
```JS
// Request
POST /lbryapi HTTP/1.1
Host: localhost:5279
Content-Type: application/json
Cache-Control: no-cache

{
	"jsonrpc": "2.0",
	"method":"channel_list_mine",
	"params": {}
}

// Response
{
    "id": null,
    "jsonrpc": "2.0",
    "result": []
}
```

**Comment by btzr-io** [comment]
I can confirm this is working with the `lbry-cli`, I'm still not sure if the `api` should do the same ?

**Comment by hackrush01** [comment]
Thanks. I think the behavior should be consistent across the API and CLI. I
probe into the issue.

Kind Regards
Amit Tulshyan

**Comment by alyssaoc** [comment]
@hackrush01 Can you look into this, is it a quick change?

**Comment by hackrush01** [comment]
@alyssaoc Sure, I will look into it.

**Comment by hackrush01** [comment]
When calling a deprecated command using API(curl etc) it prints out the deprecation message in the log as warning, like so: `2018-09-05 23:55:41,856 WARNING  lbrynet.daemon.auth.server:521: API function "daemon_stop" is deprecated, please update to use "stop"`
To change this behaviour to return the deprecation message in the API response will require some changes. Which I don't think should be done.
Pinging @jackrobison though to know what he thinks.

**Comment by alyssaoc** [comment]
closing, issue resolved
