### ISSUE TITLE
Revisit wallet_prefill_addresses command

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1278]
## The Issue
Do we really want this function creating multiple wallet addresses, or should it be sending multiple inputs to the same address? This is effectively the same result, but without the address bloat, right? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
Depends on the use case for this command. What is the use case for this command?

From looking at the code the command does what I'd expect it to do.

I can see this type of command being useful in a high throughput services where you want to be able to handle a lot of new TXs without running out of TXOs.

If you have 1 TXO valued at 10 credits. That means you can only do 1 TX at a given point in time spending up-to the 10 credits. Using this command you can ask to have the 10 credits spread across 5 new addresses each with 2 credits. Now you can create 5 TX each spending up-to 2 credits simultaneously. This is useful for spee.ch to increase throughput.

My preference would be to drop this command altogether and just make it possible to do it with two new / updated commands: 1) a command to fetch `X` number of unused addresses and 2) a command that takes an amount and a list of addresses to pay that amount to. This would allow a user to replicate what `wallet_prefill_addresses` does but in a more configurable way (for example, instead of just unused addresses, a user may want to use other heuristics to figure out which addresses they want to fund... or maybe they just want to pay the same amount to a bunch of people, etc).

**Comment by tzarebczan** [comment]
@nikooo777 we should confirm that the new `fund` command works for your YT sync scenario when we test the wallet.

**Comment by tzarebczan** [comment]
Tested on new wallet (on spee.ch), doesn't look right:
lbrynet-cli wallet_prefill_addresses 50 .04

and this was the result (I was expecting 50 UTXOs with 0.04):
https://explorer.lbry.io/tx/cb08b32de15b003e7930ced91e7226a02f6e8fab53ddabd3709947bee6b950fe
