### ISSUE TITLE
cli auth integration test

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry#1336]
Add an integration test verifying that the CLI can successfuly negotiate the authentication protocol with daemon and execute a command.
1. start daemon with authentication enabled
2. successfully connect and authenticate with it

**Comment by hackrush01** [comment]
This is a bit more involved than I originally thought. After many different permutations and combinations of trial and error, it seems like there might be some other things that need to be changed in order to make this work. One such thing seems to be AuthAPIClient. I will update this thread if something else is discovered.
