### ISSUE TITLE
account_max_address_gap is off by one

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1463]
## The Issue
When account_max_address_gap reports values for gaps, they won't work unless you add 1 to each gap.  I believe @eukreign is aware of this. Should be fixed before https://github.com/lbryio/lbry/issues/1459

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by eukreign** [comment]
The gap reported by `account_max_address_gap` is the consecutive number of unused addresses. If you have five addresses: 1, 2, 3, 4, 5. And addresses 2, 3, 4 have no transactions then the gap reported is 3. In order to correctly sync, you need to take the exclusive gap number returned by `account_max_address_gap` and +1 to have it catch the next used address and force the address generator to keep going.

As I've discussed with @tzarebczan before, I added `account_max_address_gap` mainly for debugging and not so much for users to help with setting the value because the command only works after you've already properly sync'ed your wallet. It's a chicken and egg problem: if you've already successfully sync'ed your wallet then you don't need `account_max_address_gap` and at the same time `account_max_address_gap` will not produce the correct result until you've successfully sync'ed your wallet.

My preference would be to drop this command altogether and instead put emphasis on this solution working well: https://github.com/lbryio/lbry/issues/1459
