### ISSUE TITLE
claim_list_by_channel API returns inconsistent results

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry#1477]
## The Issue
The claim_list_by_channel api call returns inconsistent results.  If I call it with only a URI then it returns a single value like this:

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "lbry://@OTR": {
      "claims_in_channel": 94
    }
  }
}
```

However, if I request a specific page I get the same value, claims_in_channel, but now it's a completely different type (a list of Claims).  I don't see the benefit in having this return the number of claims (there is another API, resolve, that returns the number of claims when passed a channel URI).  This API should either return the first page of results (if no page was specified), or make the page parameter required.  

The change of type doesn't help the caller to know why the results aren't as expected, the documentation mentions both types for claims_in_channel without indicating when the number version will be returned, and the integer return does not match the name of the API call (which specifically has "list" in the title).

It would be useful information in the normal return to say how many total items there are.  This would give a UI a way to create a page select list (total number / page size == number of total pages).  The API could return a "total_number_of_claims" or "total_claims_in_channel" value.  I also think the name of this value should match the one returned by the resolve API.

**Comment by tzarebczan** [comment]
@42degrees good point, the resolve call does show the number of claims in a channel, so we should eventually remove that functionality from the claims_list_by_channel command and have it stick to showing claims. The app currently uses claim_list_by_channel to get the claim count, so that will need to be updated. 

I'm not sure about returning the total count with the page calls - this would cause the wallet server to have to "know" about all the claims, and not just the ones on the page, which is a more expensive operation. @shyba / @jackrobison might have a better grasp of how that works.

**Comment by tzarebczan** [comment]
This was updated on the app side to no longer use claim_list_by_channel without a page value (which was used to resolve total # of claims). We are now using resolve to do so. The call/documentation can be simplified now.

**Comment by alyssaoc** [comment]
closing, reopen if needed
