### ISSUE TITLE
Change the Passing of a JSON String to `max_key_fee` in the CLI to Something Simpler

### ISSUE THREAD

**Issue by walidmujahid** [lbryio/lbry#1527]
From: https://github.com/lbryio/lbry/blob/master/lbrynet/conf.py#L261-L262

> Writing json on the cmd line is a pain

In order to provide a simpler experience for those using the API server's CLI, I think reducing the need to pass JSON strings and replacing it with another option is an important step.

For setting the `max_key_fee` via CLI here is the current syntax:

`lbrynet settings_set --max_key_fee="{\"currency\": \"USD\", \"amount\": 60}"`

However, I think it would be better if it is simplified to something like:

`lbrynet settings_set --max_key_fee "USD" 60`

Or, as was suggested in the TODO comment linked on the first line of this issue:

`lbrynet settings_set --max_key_fee "USD:60"`

Simplifying this would also make experience using other functionalities better. 

Example, to disable the max_key_fee, you have to pass in ` --disable_max_key_fee=True`. 

I have a pull request - https://github.com/lbryio/lbry/pull/1507 - that removes the need to that and rolls the functionality into `--max_key_fee` where to disable it all you have to do is pass in the amount as a `-1` -or for technical accuracy, anything below zero. 

Now, passing in a JSON string to the for disabling would be equally as annoying as setting it. So, imagine just doing:

`lbrynet settings_set --max_key_fee "USD" -1` or `lbrynet settings_set --max_key_fee "USD:-1"`

Regrading which syntax to change to -I mentioned two above-, I am a bit torn. I think the colon delimited string is fancy, but simply passing in a string and an integer would seem to work just as well.

**Comment by tzarebczan** [comment]
Thanks for opening this, appreciate the follow through!

**Comment by lyoshenka** [comment]
I would prefer the following:

```
lbrynet settings_set --max_key_fee "1.23 USD"
lbrynet settings_set --max_key_fee "4.56 LBC"
lbrynet settings_set --max_key_fee "none"
```

First change is putting the currency after the number. This makes the value more readable.

Second change is using a space instead of a colon. Either works, but spaces are more readable.

Last change is not using `-1` to mean "no value" (this is called a sentinel value). Using sentinel values should be avoided in general because it conflates two separate ideas(the actual amount and whether the amount is set) and increases the chance of mistakes. It is better to use something that's outside the range of valid responses (like "none"). It would be even better to use a `--no-max_key_fee` flag to indicate that the value is not set, but if we wanted to do that, we would have to implementing it consistently across the whole API.

More info, from the guy who started it all: https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare

**Comment by walidmujahid** [comment]
> ```
> lbrynet settings_set --max_key_fee "1.23 USD"
> lbrynet settings_set --max_key_fee "4.56 LBC"
> lbrynet settings_set --max_key_fee "none"
> ```

I agree that this is more readable @lyoshenka.

What is funny about you mentioning that it would be better if we had a `--no-max_key_fee` is that actually had a `--disable_max_fee_key`. However, it was removed in  PR #1507 based on issue/task #929.

The question is, should the option be returned? 

To me, I kind of like `lbrynet settings_set --max_key_fee "none"` as opposed to `lbrynet settings_set --disable_max_key_fee=True`. Though, I may be a bit biased. Perhaps the solution would simply be rework it so the user just has to `lbrynet settings_set --disable_max_key_fee` instead of the previous?

Any input? @eukreign, @tzarebczan, others.

**Comment by eukreign** [comment]
> I would prefer the following:
> 
> ```
> lbrynet settings_set --max_key_fee "1.23 USD"
> lbrynet settings_set --max_key_fee "4.56 LBC"
> lbrynet settings_set --max_key_fee "none"
> ```
> First change is putting the currency after the number. This makes the value more readable.
> 
> Second change is using a space instead of a colon. Either works, but spaces are more readable.
> 
> Last change is not using `-1` to mean "no value" (this is called a sentinel value). Using sentinel values should be avoided in general because it conflates two separate ideas(the actual amount and whether the amount is set) and increases the chance of mistakes. It is better to use something that's outside the range of valid responses (like "none"). It would be even better to use a `--no-max_key_fee` flag to indicate that the value is not set, but if we wanted to do that, we would have to implementing it consistently across the whole API.

Dropped `--disable-max-key-fee` as a separately stored boolean and instead there is just `max_key_fee: null` in the daemon_settings.yml, since setting things null via command line is difficult there is new `--no-max-key-fee` which sets `max_key_fee: null`. Also, passing a new max key fee via cli is now using this format: `--max-key-fee 3.0 USD` (in daemon_settings.yml it remains unchanged for backwards compatibility)

https://github.com/lbryio/lbry/pull/1815
