### ISSUE TITLE
Investigate why peer_list only returns no or single result

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#1625]
## The Issue
@jackrobison noticed that peer list only returns a single result and sometimes no results for blobs that were recently announced. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jackrobison** [comment]
It would return no result because of https://github.com/lbryio/lbry/issues/1638

It will currently return a minimal result (the amount returned from the first peer with a peer for the hash).  https://github.com/lbryio/lbry/pull/1645 will update the iterative find class to continue traversing the network after it's found a result if so desired. This will allow the peer protocol client to keep trying new peers and without restarting the search from scratch. It will also allow `peer_list` to return up to an amount (default of `k` - 8) of fresh results instead of a single or cached results.
