### ISSUE TITLE
PKG Installer for mac

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#589]
Suggestion from Jacob: convert app into pkg installer using this:

`sudo pkgbuild --install-location /Applications --component /Volumes/LBRY\ 0.9.1/LBRY.app LBRY.pkg`

**Comment by sprig** [comment]
Please do not convert to a pkg installer! Those are disgusting and terrible!

**Comment by lyoshenka** [comment]
Thanks for the feedback. Do you have specific reasons for why dmg is better than pkg?

**Comment by sprig** [comment]
A dmg is standalone. You mount it, copy the .app and run it. A pkg typically requests superuser permissions and you do not know what it does ahead of time. It is always more suspicious and unless there are specific reasons why I must use the software or understand why it needs the extra permissions, I would be hesitant to grant them.

**Comment by sprig** [comment]
Plus, the vast majority of software for OSX is installable via dmg rather than pkg.

**Comment by lyoshenka** [comment]
Those are good points. @jackrobison thoughts? (he's our resident mac expert)

**Comment by sleepdefic1t** [comment]
@sprig does have a good point.

What may be a bit more "Mac-Friendly" would be to have a daemon app.
It could run in the background via a status bar application, even launch the GUI from there.

**Comment by charlie-c** [comment]
*adding Slack discussion on this with @lyoshenka*

charlie-c [9:52 AM] 
1. Do you really *want* a pkg installer rather than dmg? If so, what do you hope to gain?
2. Do you want the pkg installer to do the same thing as is currently done (App with embedded lbrynet-daemon), or do you want lbrynet-daemon handled more like a *real* daemon, i.e. separate from the app and managed by launchd (I presume on a per-user basis rather than a global daemon for all users).

charlie-c [9:53 AM] 
hope that makes some sense

grin [4:53 PM] 
to be honest, im not sure we want a pkg installer. several people have told me dmg is more standard and better in that it doesnt require root

[4:53] 
then again, there are upsides to pkg too, right?

[4:53] 
im much more of a linux dev

charlie-c [4:54 PM] 
that’s why I wanted to ask, as I saw the discussion on the github issue.

grin [4:54 PM] 
im open to hearing arguments for either side

charlie-c [4:55 PM] 
dmg has these advantages: very simple, everything is contained inside an App, which is just dragged into Applications area, so nothing to it really - uninstall is just assumed to be “delete the App”.

[4:56] 
pkg has these advantages: can do more complicated things, install different components to different places, libs, etc., daemons, and use the system level services to launch/kill/restart and otherwise maintain operation of the daemon.

grin [4:58 PM] 
we'd like the daemon to start on startup and run as a standalone process

[4:58] 
but this may be farther in the future

charlie-c [4:58 PM] 
on startup of… ??

[4:58] 
user login?

grin [4:58 PM] 
when you restart your laptop

[4:59] 
not sure if dmg/pkg affects that

charlie-c [4:59 PM] 
ok, so 2 things

[4:59] 
1. yes, it does, you’d want a pkg installer for that so you can schedule the daemon with launchd.

[5:03] 
2. I’m not familiar enough with libry, so don’t know how it does authentication, i.e. *who* is sending it json requests. If it is assumed to be the daemon owner (i.e. who started it), then it may not be suitable as-is for running on laptop startup, i.e. as root or an unprivileged user…

[5:04] 
what’s done on linux? does it run as a daemon at machine boot time?

grin [5:05 PM] 
no, that doesnt happen on any os right now. but we want that to happen in the future. im not exactly sure how i'd do it. it would either be through systemd or through however gnome does it

[5:06] 
there's some support for authentication but its off by default and nothing uses it

[5:06] 
so the daemon just trusts any requests it gets right now

charlie-c [5:06 PM] 
yup, you can think of launchd on osx as similar in scope to systemd…

grin [5:06 PM] 
gotcha

charlie-c [5:09 PM] 
cool - I think that covers it for the moment - I’ll add this discussion to the issue if that’s ok with you, and it can be continued from there…

grin [5:09 PM] 
yes, that would be great

[5:09] 
i think that for now we're fine keeping it a dmg, but we may want to switch to pkg in the future

[5:09] 
i really like that you don't need root for dmg

[5:09] 
and that its simple

charlie-c [5:10 PM] 
yes, it is very simple, it’s designed for Apps with essentially no subcomponents (associated processes), i.e. standalone.

[5:11] 
I’m only raising the issue because I saw the bounty and thought it would be a nice little project to get my feet wet with lbry development, a first project…

[5:11] 
anyway, cheers for the help…

**Comment by sprig** [comment]
I would like to add something;

It is correct that to add a system level daemon would require a pkg.
However, I *think* that most often OSX computers are not used as headless
servers but rather as workstations, and as such are usually logged in to a
user almost all the time that they are working. Now, if the lbry daemon
were to live in the taskbar (where apps like e.g. dropbox, google drive
live while not "open" in an actual application view), it could be launched
at user login - still without pgk required - and also managed more easily
by users (i.e. without dropping to a shell).

**Comment by sleepdefic1t** [comment]
It's dropping to a shell..
But I just posted this for macOs

[lbryBuilder](https://github.com/sleepdefic1t/lbryBuilder)

It's basically two scripts.

One to do the cloning and setup.  
It prompts to launch the daemon from its venv in a new terminal window.

Another to run an instance of the daemon from its venv.

Not sure if this would help, but it seems at least semi-relevant.

**Comment by kauffj** [comment]
Given that all Mac usage will be consumer usage (as @sprig said). It sounds like the only downside of DMG is losing out on management via `launchd`.

Is there anyone out there interested in taking the pro-PKG side of this argument?

**Comment by sleepdefic1t** [comment]
@kauffj

I can't really think of one.
Apple is very sandboxed.
I forget what part of their docs, but I remember seeing they discourage having executables that easy to access unless it's absolutely necessary.
A guest account making calls to the daemon from outside the users desktop, for example.

If the primary goal is just to have it run as a standalone.
That's not too difficult.

I've actually kinda been working on something I keep calling "lbryun" (librarian).
Standalone statusbar app that runs the daemon, can launch the UI, and a lbrycrd concept I've been wanting to play with.

I've got LBRY source packaged and bundled as LBRYKit, daemon running with cli working.
I'm currently hammering out venv & daemons queuing and such.

I plan to have the project posted soon, but I wanna make sure it's not complete shit before i start the repo.

**Comment by kauffj** [comment]
@sleepdefic1t I'd be very interested in status bar support for `lbry-app`, but my inclination would be to make this part of the app itself rather than a standalone. Either way, sounds interesting and please share the code! And if you're not in the #dev channel in our [Slack](https://slack.lbry.io), you should join!

**Comment by lyoshenka** [comment]
We're gonna stick with a DMG installer. Thanks @sprig and @charlie-c for convincing us.
