### ISSUE TITLE
Daemon start fails if port is already bound 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#710]
## The Issue
If there are other services running on the typical daemon port (and possibly on 3333/4444), the daemon will fail to load. 
### Steps to reproduce
1. Run claymore miner
2. Run lbry. 
3. Receieve error

### Expected behaviour
Port should be incrementally revised until a free one is found. User should be made aware of any non default ports. (I.e if it's the daemon port, the api call will be different, if it's the sharing port, port forwarding may need to be adjusted) 

### Actual behaviour
Daemon fails. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Here is a log of the issue occurring: https://github.com/lbryio/lbry/files/1103576/lbrynet.3.log.txt

**Comment by kaykurokawa** [comment]
Ports to bind to should never automatically change to some other random port. This is poor practice because people need to write firewall rules which requires fixed port numbers. It also makes testing the service on the port impossible because it could be bound to some random port that the client has no knowledge of. 

It definitely should give proper feedback if it failed to bind to a port, and probably include instructions on how to change the port through the config file.

**Comment by tzarebczan** [comment]
@hackrush01 It should alert the user that the port is already bound and explain how to change the port.
 
@kaykurokawa  / @jackrobison How would this port change be done with the app?

**Comment by kauffj** [comment]
It doesn't even need to explain how to change the port at this point. I suppose it could spit out a link to a FAQ page or similar.

At this time, I'm not concerned with getting port changing inside of the app. All I'd like to see for now is a clean exit and user feedback alerting about the issue.

**Comment by lyoshenka** [comment]
Fixed by https://github.com/lbryio/lbry/pull/749
