### ISSUE TITLE
send_amount_to_address does not send transaction immediately, does not return txid

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#719]
`send_amount_to_address` queues the transaction, but it should send the transaction immediately and return the txid. I had a situation where I started the daemon and called `send_amount_to_address`. The cli said "true". Then I shut down the daemon. Turns out the transaction was not actually sent.

Bare minimum fix: have `send_amount_to_address` say something like "Payment queued", so at least you know it has not been sent yet.

Real fix: send payment right away, don't queue it. Return txid. Daemon should also flush the queue on shutdown, so no payments are dropped.

**Comment by kaykurokawa** [comment]
I think its important to remove the  payment queueing feature in the Wallet as it is causing a host of issues. 

As you said, payments will get dropped on shutdown which is a huge issue. Only way to fully solve this is writing queued payments to disk immediately. 

Another issue is https://github.com/lbryio/lbry-app/issues/117 , since lbryum Wallet is the only module that can tell you whether you have enough credits for updates, it is very problematic from a programming perspective that we have a separate queued payments to consider outside of the lbryum module. 

Users are also reporting multiple related issues of their balance being wrong here:
https://github.com/lbryio/lbry/issues/640
https://github.com/lbryio/lbry/issues/538

**Comment by kauffj** [comment]
This previously had next release and Kay thinks this is important, so I marked P1.

**Comment by kaykurokawa** [comment]
started on it here https://github.com/lbryio/lbry/pull/747

**Comment by lyoshenka** [comment]
Next step: figure out the proper way to fix this, so we know what to do next

**Comment by hackrush01** [comment]
I was checking out some stuff on my local regtest server, and I found out that the transaction only begins when a new block is created. I think that's why it takes doesn't send the transaction right away as it waits for the announce of a new block being found. I think this may have to do with the way the blockchain works. Can you please try this out and see if you can replicate?

**Comment by alyssaoc** [comment]
will be addressed in new wallet
