### ISSUE TITLE
Straighten out metabase/loggly logging, then figure out next step in diagnosing download errors

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#774]

**Comment by tzarebczan** [comment]
This is important as it may be filling up users log files.

I was getting the following spammed in mine, possibly after a connection issue:
ConnectionError: HTTPSConnectionPool(host='logs-01.loggly.com', port=443): Max retries exceeded with url: /inputs/adf4e86a-6904-4b36-97f2-0fa837d8dc0b/tag/lbrynet-0.14.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0F082D70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

  Is this something on the loggly side or in the app?

**Comment by lyoshenka** [comment]
@jackrobison is this done? What are the next steps in diagnosing download errors?
