### ISSUE TITLE
Investigate and write up comparison of possible solutions to proof-of-purchase problem

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#782]
As a developer, I want to understand the possible solutions to the proof-of-purchase issue so I can intelligently compare them and  decide which is  best

**Comment by kauffj** [comment]
@jackrobison and I have a very different understanding of what we're addressing with this ticket. I've asked him to stop working on it until we meet and discuss. @lyoshenka

**Comment by jackrobison** [comment]
@kauffj @lyoshenka 

>user can be charged for content, even if content download fails. then user gets charged again in the future.

>user can delete content they paid for, then try to download it again. they will be charged again.

>user can switch computers

>content can change. in this case, user might NOT be charged again?

I think there are three sides to this problem:
1. As a _downloader_, how do I avoid paying multiple times for the same thing, or paying for something I do not receive?

2. As a _publisher_, how do I enforce key payments  by downloaders?

3. As a _host_, how do I enforce the data rates that downloaders agreed to pay me?

I think this issue is really looking at 1, which does have a simple solution (add the information to the database). However, I think this issue _should_ be looking at 2 and 3, which are much deeper and involve protocol changes.

A proof of payment is something that can be communicated to and verified by someone else, without trust; so I think 1 should be broken out from the "proof of payment" issue and made into a smaller issue of its own.

**Comment by lyoshenka** [comment]
Agreed with your assessment. In fact there are probably even more parties involved. I'll add these to the top-level issue and close this one.

**Comment by lyoshenka** [comment]
Actually... only somewhat agreed. The simple solution only works because there's no reputation or payment tracking system in place yet. But that's where we're at now, so that will be good enough.
