### ISSUE TITLE
download_path is incorrect for files uploaded from outside of download directory

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#827]
@tzarebczan commented on [Fri Jul 28 2017](https://github.com/lbryio/lbry-app/issues/400)

**Edit by Jeremy**: Tom's description is below. The root issue here is that the `download_path` property returned by `file_list` is incorrect for uploaded content. In fact, `download_path` isn't really a great name for this property, and should probably instead be called something like `file_path`.

## The Issue
Both Open and "Open in Folder" fail to work properly for locally published content if it was uploaded from outside of the Downloads directory. Also, the content may not open or stream correctly, because it doesn't know where the file is. There is also the 

### Steps to reproduce
1. Upload a file from your desktop
2. Go to your claim
3. Click Open or Open in Folder (using .... ) 
4. Fails on Open, Open in Folder brings you to downloads
5. Click Stream (if video) - fails if on the channel page (a different isssue issue), otherwise it tries to download / re-create the content in the Downloads folder. 

### Expected behaviour
Either show not allow "Open" for own content, or needs to be aware of where the content was uploaded from (but it could be removed from there later too!!)

### Actual behaviour
Nothing

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
This https://github.com/lbryio/lbryum/issues/143 is sort of related because users try to stream their own content and it fails.

**Comment by eukreign** [comment]
There are a couple of possible solutions to this:

1. **Only allow publishing from Downloads directory.** This would have the added benefit that we could automatically present the user with the list of newly added files that are not yet published (instead of having them go through file manager every time). Also, one could make the argument that keeping lbry isolated to one directory is better for security.

2. **Keep a local mapping of file hash to file path and check this before generating / downloading files to Downloads directory.** This solution directly addresses this original issue but there may be a lot of new edge cases it creates (if a user has lbry installed on more than one computer, then on the original computer from which they uploaded the file it will be in one place and on the second computer it will automatically go into Downloads directory... unless they sync the file path mapping to the second computer).

3. **Store the original file path in the file meta data.** I think this would be the worst solution since it exposes the users private directory structure to the outside world.

I think option 1 is the best because it has clear and obvious workflow for users and for developers with the least amount of edge cases.

**Comment by lyoshenka** [comment]
this will be fixed by #505

**Comment by lyoshenka** [comment]
i meant #1025

**Comment by jackrobison** [comment]
Fixed in https://github.com/lbryio/lbry/pull/1025
