### ISSUE TITLE
Consolidate wallet configuration into same folder as LBRY config

### ISSUE THREAD

**Issue by jobevers** [lbryio/lbry#83]
Its confusing to users to have a folder for LBRY configuration, lbrycrd configuration and lbryum configuration.  We could consolidate all of them into one.

**Comment by jsophrin** [comment]
A script that just makes a backup of the wallet files wherever they are and have it located int he settings area of the lbry, so that other people avoid this situation.

Apart form FAQ, new users at least testers and engineer advanced user folks that are not familiar with the structure of the application and its supporting files may need a more detailed visualized overview of where components are located and their relationship to one another. Maybe not the complete nitty gritty, but the main components at least so that troubleshooting and navigation is a little easier.
