### ISSUE TITLE
IPFS integration 

### ISSUE THREAD

**Issue by i5heu** [lbryio/lbry#881]
I think IPFS is at the moment the best P2P Protocol for Media.
Its available for Python Golang and JS.
[IPFS](https://github.com/ipfs/ipfs)

Maybe its better to concentrate the Open Source Developer on one P2P library, intend of a dozends.

So does the lbry team want to integrate IPFS?
Are there Plans?

**Comment by tzarebczan** [comment]
This is the current analysis of ipfs vs lbry protocol https://lbry.io/faq/different-ipfs

**Comment by eukreign** [comment]
We are not currently planning to add IPFS support; we'll re-open this issue if that changes.

**Comment by RubenKelevra** [comment]
> This is the current analysis of ipfs vs lbry protocol https://lbry.io/faq/different-ipfs

Hey @tzarebczan,

I was thinking about how IPFS can improve on the shortcomings to get your support!

#### Collaborative Cluster 

There is probabilistic pinning which would make it much easier to scale an ipfs cluster with stored videos:

https://github.com/ipfs/roadmap/issues/84

This could be an community driven approach to store the videos, by having people [join a collaborative cluster](https://blog.ipfs.io/2020-01-09-collaborative-clusters/) reducing the dependency on server of a single entity storing the data for the videos.

Additionally to the cluster all viewers of a video would store them in their cache for a while. Which results in hot content stored in many places, while cold content is relying on the cluster to be available.

To avoid having the cluster filled up with too much stuff in the long run, artists could be asked to pay a small fee per month and for each 100 MB. If the fee is not paid the content is unpinned from the cluster and the content creator is responsible to store it somewhere on the network itself.

The fee could be used to pay for the pinning/unpinning infrastructure first, and then just add space to the cluster to get a sustainable grow.

This would allow a creator to put his content on any pinning service he likes, or just select the community driven cluster. 

#### Human readable URLs

- I've started [a discussion](https://discuss.ipfs.io/t/ipfs-human-readable-urls-use-a-dht-to-upgrade-urls-to-ipfs-cids/10209) some days ago on how to improve the discoverablility of content on IPFS by adding a DHT which can resolve URLs/URIs published by nodes, secured by an anchor (for the signature) on the dns system.

This would allow you to publish the current URLs with minimal changes to IPFS and having all IPFS nodes able to resolve them directly in the network without asking an HTTP-Server.

#### Conclusion

I would really see both projects work together and having the ability to spend some terabytes of storage to the lbry project! Is there anything else blocking the migration to IPFS if those two features would be implemented? 🤔

I only see the lack of payment infrastructure. But I think your payment system is storage system agnostic. So it could be put on an IPFS cluster as well? 🤔

Thanks in advance for taking the time to reconsider your decision!

**Comment by RubenKelevra** [comment]
> To avoid having the cluster filled up with too much stuff in the long run, artists could be asked to pay a small fee per month and for each 100 MB. If the fee is not paid the content is unpinned from the cluster and the content creator is responsible to store it somewhere on the network itself.
> 
> The fee could be used to pay for the pinning/unpinning infrastructure first, and then just add space to the cluster to get a sustainable grow.
> 
> This would allow a creator to put his content on any pinning service he likes, or just select the community driven cluster. 

Additionally to the small artist fees to put stuff onto the community cluster for guaranteed availability. All nodes which offer storage and bandwidth to the network could be getting small tips by the viewers. 

Maybe say 0.005 coins per GB of traffic. 

The viewers would record how much they have received from which ipfs node and when a certain threshold is met, like half a coin, they are send to the owner of the node. 

This needs a way to store crypto currency addresses in the ipfs nodes, or sign them with the node key and put them in the lbry profile. 


While not mandatory to keep fee on and while it could not be enforced anyway, much of the content is already payed by good will, too. So I think the viewers will understand that this small payments are a necessity to a sustainable grow of the network. 

This would also help to attract users to keep their caches as large as possible or join the cluster.

### Browser integration 

Since IPFS can be integrated into the browser Odysee.com could fetch the video directly via the local ipfs node, while the site itself is fetched via https. This offloads the bulk of the traffic from the web infrastructure.
