### ISSUE TITLE
Drop disable_max_key_fee

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry#929]
If `max_key_fee` is set, I have a max key fee. If it's not, I don't.

There's no need to use two values for this.

**Comment by walidmujahid** [comment]
If no one has taken this task on already, I would like to add it to the tasks/issues list I will be working on.

**Comment by tzarebczan** [comment]
This is a good one to start with, thanks for grabbing it!

**Comment by walidmujahid** [comment]
https://github.com/lbryio/lbry/issues/1527

**Comment by eukreign** [comment]
Dropped `--disable-max-key-fee` as a separately stored boolean and instead there is just `max_key_fee: null` in the daemon_settings.yml, since setting things null via command line is difficult there is new `--no-max-key-fee` which sets `max_key_fee: null`. Also, passing a new max key fee via cli is now using this format: `--max-key-fee 3.0 USD` (in daemon_settings.yml it remains unchanged for backwards compatibility)

https://github.com/lbryio/lbry/pull/1815
