### ISSUE TITLE
file_list not updated after claim update

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#944]
## The Issue
This issue stems from https://github.com/lbryio/lbry-app/issues/600

After a claim is edited, the updated file information does not make it into file list.  So once the transaction is confirmed, the app can't find the file based on the new outpoint since the txid has been updated. 

Need to do some research about how/when the file information is updated in file_list, but this looks like a bug right now. Not sure if file_list should be updated immediately or once the transaction has been confirmed. Issue 600 only surfaces while the tx is in pending, as it still compares the original output until then. It is definitely updated after an app reboot. 

### Steps to reproduce
1. Create claim, check file_list
2. Edit claim, wait for confirmation
3. Check file_list - still same data
4. Restart app, check file_list - updated

### Expected behaviour
File_list should be updated 
### Actual behaviour
File_list not updated until restart

## System Configuration

 

- LBRY Daemon version: 0.17rc3
- LBRY App version: 0.17rc1
- LBRY Installation ID:
- Operating system:

**Comment by kaykurokawa** [comment]
The correct behavior of file_list should be that it is never affected by any claim state (updating and abandons should have zero effect on what file_list produces). Files are just files, and they can and do exist without being attached to a claim (i.e., when reflector obtains it from clients)

If you need to look for a specific file attached to a claim. You should look up the claim's sd_hash and then use the sd hash to look for the specific file.   

I would like to remove these fields from the file_list command:  name, outpoint, and claim_id, 
This will remove the file manager's dependency on wallet commands which can slow down file_list to a crawl for a node with a large amount of files (happens on reflector hosts).

**Comment by tzarebczan** [comment]
I think I agree with what you are saying, as that's not what is happening now. We do need to take into account the scenarios where a claim may receive an updated source file - how would that look like to a user who already had downloaded content from that claim? Or maybe we need to force a new claim Id if the content is updated, dunno.

But the behavior of file_list is definitely breaking core functionality of the app as it is implemented currently.

**Comment by kaykurokawa** [comment]
You have to use "resolve" in order to know if a name has been updated. 

You "resolve" the claim, and check if you have the source file by using "file_list" with sd hash. 

I think the app is just using the "name" field in the file_list to check if it already has the file for a name. It needs to stop doing that, because that's wrong.

**Comment by lyoshenka** [comment]
related to #1025

**Comment by jackrobison** [comment]
Fixed in 0.19.0

When a publisher updates their claim the stream and associated metadata update with it - they start with one file and end with one file. When someone who downloaded the previous claim sees the new update they also update the associated metadata, so long as it does not change the stream. An update with a new stream must be downloaded as a second file.
