### ISSUE TITLE
Rewrite lbry in Rust

### ISSUE THREAD

**Issue by Serkan-devel** [lbryio/lbry#997]
Rewriting in Rust would give lbry the speed of C/C++ combined with the safety of an expressive type system like Java.

**Comment by lyoshenka** [comment]
@Serkan-devel are you interested in tackling this? Type safety would be great to have, and we've been thinking about it too. We would prefer Go instead of Rust, but we're open-minded. This is not a priority for us for the foreseeable future, but if you do it, we're happy to pay a bounty for the work.
